module.exports = {
    pkgs: [
        'create-fes-app',
        'fes',
        'fes-compiler',
        'fes-preset-built-in',
        'fes-builder-vite',
        'fes-builder-webpack',
        'fes-runtime',
        'fes-utils',
        'fes-plugin-access',
        'fes-plugin-enums',
        'fes-plugin-icon',
        'fes-plugin-jest',
        'fes-plugin-layout',
        'fes-plugin-locale',
        'fes-plugin-model',
        'fes-plugin-monaco-editor',
        'fes-plugin-qiankun',
        'fes-plugin-request',
        'fes-plugin-sass',
        'fes-plugin-vuex',
        'fes-plugin-pinia',
        'fes-plugin-windicss',
        'fes-plugin-watermark',
        'fes-plugin-login',
    ],
    copy: [],
};
