<template><h1 id="contributing-guide"><a class="header-anchor" href="#contributing-guide">#</a> Contributing Guide</h1>
<h2 id="overview"><a class="header-anchor" href="#overview">#</a> Overview</h2>
<p>This repository employs a <a href="https://en.wikipedia.org/wiki/Monorepo" target="_blank" rel="noopener noreferrer">monorepo<OutboundLink/></a> setup with <a href="https://classic.yarnpkg.com/en/docs/workspaces" target="_blank" rel="noopener noreferrer">yarn classic workspaces<OutboundLink/></a>, and hosts a number of associated but separated packages in the <code>packages</code> directory:</p>
<ul>
<li>
<p><code>@vuepress/core</code>: The VuePress core. Provides pure Node API to generate VuePress app, including page handling, plugin system and data preparation.</p>
</li>
<li>
<p><code>@vuepress/client</code>: The VuePress client package. Provides the client entry, and exports types and composable utils that can be used in client side development.</p>
</li>
<li>
<p><code>@vuepress/bundler-webpack</code>: The VuePress bundler package with webpack. Use webpack to <code>dev</code> and <code>build</code> VuePress app that generated by <code>@vuepress/core</code>.</p>
</li>
<li>
<p><code>@vuepress/cli</code>: The VuePress command line interface (CLI) package. It will resolve user config file, and create VuePress app with <code>@vuepress/core</code>, then use <code>@vuepress/bundler-${name}</code> to execute corresponding command.</p>
</li>
<li>
<p><code>@vuepress/theme-default</code>: The VuePress default theme.</p>
</li>
<li>
<p><code>@vuepress/plugin-${name}</code>: Official plugins.</p>
</li>
<li>
<p><code>@vuepress/shared</code>: Utilities that shared between node side and client side.</p>
</li>
<li>
<p><code>@vuepress/utils</code>: Utilities that should only be used in node side.</p>
</li>
<li>
<p><code>vuepress</code>: Simply a wrapper of <code>@vuepress/cli</code>, which requires <code>@vuepress/bundler-webpack</code> and <code>@vuepress/theme-default</code> as dependencies. If users want to use default theme with webpack, they can simply install this package.</p>
</li>
</ul>
<h2 id="development-setup"><a class="header-anchor" href="#development-setup">#</a> Development Setup</h2>
<p>Pre-requirement:</p>
<ul>
<li><a href="http://nodejs.org" target="_blank" rel="noopener noreferrer">Node.js<OutboundLink/></a> <strong>version 12+</strong></li>
<li><a href="https://classic.yarnpkg.com/en/docs/install" target="_blank" rel="noopener noreferrer">Yarn v1 classic<OutboundLink/></a></li>
</ul>
<p>Clone the repo, and install dependencies:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">yarn</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>Start watching source files:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">yarn</span> dev
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>Open another terminal, and start developing the documentation site:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">yarn</span> docs:dev
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>Main tools that used in this project:</p>
<ul>
<li><a href="https://www.typescriptlang.org/" target="_blank" rel="noopener noreferrer">TypeScript<OutboundLink/></a> as the development language</li>
<li><a href="https://jestjs.io/" target="_blank" rel="noopener noreferrer">Jest<OutboundLink/></a> for unit testing</li>
<li><a href="https://eslint.org/" target="_blank" rel="noopener noreferrer">ESLint<OutboundLink/></a> + <a href="https://prettier.io/" target="_blank" rel="noopener noreferrer">Prettier<OutboundLink/></a> for code linting and formatting</li>
</ul>
<h2 id="scripts"><a class="header-anchor" href="#scripts">#</a> Scripts</h2>
<h3 id="yarn-build"><a class="header-anchor" href="#yarn-build">#</a> <code>yarn build</code></h3>
<p>The <code>build</code> script uses <code>tsc</code> to compile typescript source files to javascript dist files.</p>
<p>You may need to run this script first after your clone this repository, because the dist files are ignored by <code>.gitignore</code>.</p>
<h3 id="yarn-copy"><a class="header-anchor" href="#yarn-copy">#</a> <code>yarn copy</code></h3>
<p>The <code>copy</code> script of root project runs <code>copy</code> script in all packages, copying some resources from source directory to dist directory.</p>
<p>Some source files (e.g. <code>.vue</code>, <code>.styl</code> files) can not be processed by <code>build</code> script, but should keep the same relative path in the dist directory.</p>
<p>You may need to run this script after your clone this repository, too.</p>
<h3 id="yarn-dev"><a class="header-anchor" href="#yarn-dev">#</a> <code>yarn dev</code></h3>
<p>The <code>dev</code> script runs <code>copy</code> and <code>build</code> scripts in watch mode.</p>
<h3 id="yarn-clean"><a class="header-anchor" href="#yarn-clean">#</a> <code>yarn clean</code></h3>
<p>The <code>clean</code> script runs <code>clean</code> script in all packages, cleaning all the dist files and caches. In other words, it will remove all the files that generated by <code>build</code>, <code>copy</code> and <code>dev</code> scripts.</p>
<p>It's used before you want to re-build source files from a clean / initial state.</p>
<h3 id="yarn-docs"><a class="header-anchor" href="#yarn-docs">#</a> <code>yarn docs:*</code></h3>
<h4 id="yarn-docs-build-yarn-docs-dev-yarn-docs-clean"><a class="header-anchor" href="#yarn-docs-build-yarn-docs-dev-yarn-docs-clean">#</a> <code>yarn docs:build</code>, <code>yarn docs:dev</code>, <code>yarn docs:clean</code></h4>
<p>The <code>docs:</code> prefix indicates that these scripts are for documentation, i.e. the <code>docs</code> directory.</p>
<p>VuePress is using itself to build its own documentation site.</p>
<p>You need to run <code>yarn build &amp;&amp; yarn copy</code> to build VuePress source files first, then run these <code>docs:</code> scripts to develop and build our documentation.</p>
<h4 id="yarn-docs-serve"><a class="header-anchor" href="#yarn-docs-serve">#</a> <code>yarn docs:serve</code></h4>
<p>Serve the documentation site locally.</p>
<p>You need to run <code>yarn docs:build</code> first to generate the documentation dist files, and then run <code>yarn docs:serve</code> to serve them.</p>
<h3 id="yarn-lint"><a class="header-anchor" href="#yarn-lint">#</a> <code>yarn lint</code></h3>
<p>The <code>lint</code> script uses ESLint to check all source files.</p>
<h3 id="yarn-test"><a class="header-anchor" href="#yarn-test">#</a> <code>yarn test</code></h3>
<p>The <code>test</code> script uses Jest to run unit testings.</p>
</template>